"""add audio_duration to tts_jobs

Revision ID: 1ccaccfcb3f0
Revises: 37c7b24d235a
Create Date: 2026-08-03 01:25:25.594635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ccaccfcb3f0'
down_revision: Union[str, Sequence[str], None] = '37c7b24d235a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tts_jobs', sa.Column('audio_duration', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tts_jobs', 'audio_duration')
    # ### end Alembic commands ###
