"""add audio_duration to tts_jobs

Revision ID: 1ccaccfcb3f0
Revises: 37c7b24d235a
Create Date: 2026-08-03 01:25:25.594635

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ccaccfcb3f0"
down_revision: str | Sequence[str] | None = "37c7b24d235a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tts_jobs", sa.Column("audio_duration", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tts_jobs", "audio_duration")
    # ### end Alembic commands ###
