"""Add batch and queue fields

Revision ID: 37c7b24d235a
Revises: 
Create Date: 2026-08-01 23:49:45.370026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37c7b24d235a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tts_jobs', sa.Column('batch_id', sa.String(length=36), nullable=True))
    op.add_column('tts_jobs', sa.Column('batch_position', sa.Integer(), nullable=True))
    op.add_column('tts_jobs', sa.Column('source_file_name', sa.String(length=255), nullable=True))
    op.add_column('tts_jobs', sa.Column('source_file_size', sa.Integer(), nullable=True))
    op.add_column('tts_jobs', sa.Column('cancel_requested', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('tts_jobs', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tts_jobs_batch_id'), 'tts_jobs', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tts_jobs_batch_id'), table_name='tts_jobs')
    op.drop_column('tts_jobs', 'started_at')
    op.drop_column('tts_jobs', 'cancel_requested')
    op.drop_column('tts_jobs', 'source_file_size')
    op.drop_column('tts_jobs', 'source_file_name')
    op.drop_column('tts_jobs', 'batch_position')
    op.drop_column('tts_jobs', 'batch_id')
    # ### end Alembic commands ###
